[env:tester]
platform = https://github.com/maxgerhardt/platform-raspberrypi.git
board = rpipico2w    ; or pico, rpipicow, rpipico2 (only rpipico2w has been tested)
framework = arduino
board_build.core = earlephilhower
board_build.filesystem_size = 0.5m
monitor_speed = 115200